sudo: false
language: java
jdk: oraclejdk7
cache:
  directories:
    - '$HOME/.m2/repository'
script: cd cukedoctor-reporter && mvn clean install -Pcoverage && cd ../cukedoctor-main && mvn clean package && cd ../cukedoctor-maven-plugin && mvn clean package
