sudo: false
language: java
jdk: oraclejdk7
cache:
  directories:
    - '$HOME/.m2/repository'
env:
  global:
    - secure: "e936lcbyk8GZ/WEcliJagjsVHepDzfk51vcTy9RuTQc1Cs3dGrLAn7VudSSyudQtk4rKZ0Q1dmPoSF0lCygsQaSLOONYPEt1HUPuifZzgxr3iLmIzYU+AbJxyKALCMNtJSQKsDyMoyJerwl8C2s2SKsHQZBhDnbkDfdDYkB+NlGFQpVzyKydElc4hoatjIFigsjMU+UTGGooi44eN5PqGVsb/9UAtAZCE2APXKfbTgH08R1ml/TwA/n/279GyXu6/T9BrIgRScrhy7Yxc9pC+rtDp6QVZN0/NsPNnbuzEF1EurQSRhL6dFLOT72iiCbAxQixxXwvo47eaGNZ3kIxVHYUcTjzIRM42atlI2Ghuipm39w0DlUuou1kcOAPXXCBl7oWpxgCnkny3ibN2XDXB7sH1jTnimuDI17QI5SUAiohVZHTB90LIb4j8C/rnOCVhMFGcT3JI9TKEXIlC7udd2gLgew7v+JVvFFqpcM8kIF1Fq1yaf2bW70hiqKKvHGwGvfX2jAPDQdcY4y/vlJmpm1jR4LJXbu+tZo/1OJFShMT0P2NXsYBBFassrMNLqVJW3gb5lwVAhQ2blOHcYfjH7c+PD5rc8zMUmzV9EPfhKquDOzkJn8uEqPBcNVG8IS/zHKvpFpN/0oo1o/QT0G8lH/TbDFr/0JXccgZnYoE4T0="
script: cd cukedoctor-converter && mvn clean install -Pcoverage
        && cd ../cukedoctor-main && mvn clean package && cd ../cukedoctor-maven-plugin
        && mvn clean package && cd ../
        && mvn -Pfat-jar deploy --settings settings.xml -DskipTests=true
